[2023-11-16T11:34:21.920] [ERROR] error - Error: Field 'user_salt' doesn't have a default value
    at PromisePool.execute (C:\Users\59858\Desktop\think\think-ts-lib\node_modules\mysql2\promise.js:374:22)
    at ThinkDb.insert (C:\Users\59858\Desktop\think\think-ts-lib\dist\thinkdb.js:205:53)
    at say (C:\Users\59858\Desktop\think\think-ts\app\controller\hello.ts:13:41)
    at C:\Users\59858\Desktop\think\think-ts-lib\dist\router.js:49:50
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async exports.default (C:\Users\59858\Desktop\think\think-ts-lib\dist\error.js:12:9) {
  code: 'ER_NO_DEFAULT_FOR_FIELD',
  errno: 1364,
  sql: "INSERT INTO sys_user (user_name) VALUES ('')",
  sqlState: 'HY000',
  sqlMessage: "Field 'user_salt' doesn't have a default value"
}
[2023-11-16T11:34:58.267] [ERROR] error - Error: Field 'user_salt' doesn't have a default value
    at PromisePool.execute (C:\Users\59858\Desktop\think\think-ts-lib\node_modules\mysql2\promise.js:374:22)
    at ThinkDb.insert (C:\Users\59858\Desktop\think\think-ts-lib\dist\thinkdb.js:205:53)
    at say (C:\Users\59858\Desktop\think\think-ts\app\controller\hello.ts:13:41)
    at C:\Users\59858\Desktop\think\think-ts-lib\dist\router.js:49:50
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async exports.default (C:\Users\59858\Desktop\think\think-ts-lib\dist\error.js:12:9) {
  code: 'ER_NO_DEFAULT_FOR_FIELD',
  errno: 1364,
  sql: 'INSERT INTO sys_user (user_name) VALUES (0)',
  sqlState: 'HY000',
  sqlMessage: "Field 'user_salt' doesn't have a default value"
}
[2023-11-16T11:36:16.077] [ERROR] error - Error: Column count doesn't match value count at row 1
    at PromisePool.execute (C:\Users\59858\Desktop\think\think-ts-lib\node_modules\mysql2\promise.js:374:22)
    at ThinkDb.insert (C:\Users\59858\Desktop\think\think-ts-lib\dist\thinkdb.js:205:53)
    at say (C:\Users\59858\Desktop\think\think-ts\app\controller\hello.ts:13:41)
    at C:\Users\59858\Desktop\think\think-ts-lib\dist\router.js:49:50
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async exports.default (C:\Users\59858\Desktop\think\think-ts-lib\dist\error.js:12:9) {
  code: 'ER_WRONG_VALUE_COUNT_ON_ROW',
  errno: 1136,
  sql: "INSERT INTO sys_user (user_name, user_salt) VALUES ('')",
  sqlState: '21S01',
  sqlMessage: "Column count doesn't match value count at row 1"
}
[2023-11-16T11:49:38.614] [ERROR] error - Error: Column count doesn't match value count at row 1
    at PromisePool.execute (C:\Users\59858\Desktop\think\think-ts-lib\node_modules\mysql2\promise.js:374:22)
    at ThinkDb.insert (C:\Users\59858\Desktop\think\think-ts-lib\dist\thinkdb.js:207:53)
    at say (C:\Users\59858\Desktop\think\think-ts\app\controller\hello.ts:13:41)
    at C:\Users\59858\Desktop\think\think-ts-lib\dist\router.js:49:50
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async exports.default (C:\Users\59858\Desktop\think\think-ts-lib\dist\error.js:12:9) {
  code: 'ER_WRONG_VALUE_COUNT_ON_ROW',
  errno: 1136,
  sql: "INSERT INTO sys_user (user_name, user_salt) VALUES ('')",
  sqlState: '21S01',
  sqlMessage: "Column count doesn't match value count at row 1"
}
[2023-11-16T15:26:58.515] [ERROR] error - Error: Unknown column 'created_time' in 'field list'
    at PromisePool.execute (C:\Users\59858\Desktop\think\think-ts-lib\node_modules\mysql2\promise.js:374:22)
    at ThinkDb.insertAll (C:\Users\59858\Desktop\think\think-ts-lib\dist\thinkdb.js:262:49)
    at say (C:\Users\59858\Desktop\think\think-ts\app\controller\hello.ts:13:41)
    at C:\Users\59858\Desktop\think\think-ts-lib\dist\router.js:49:50
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async exports.default (C:\Users\59858\Desktop\think\think-ts-lib\dist\error.js:12:9) {
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sql: "INSERT INTO sys_user (user_name, user_salt, created_time, update_time) VALUES ('测试1', '2023-11-16 15:26:58', '2023-11-16 15:26:58', 'asd')",
  sqlState: '42S22',
  sqlMessage: "Unknown column 'created_time' in 'field list'"
}
[2023-11-16T15:28:08.444] [ERROR] error - Error: Unknown column 'created_time' in 'field list'
    at PromisePool.execute (C:\Users\59858\Desktop\think\think-ts-lib\node_modules\mysql2\promise.js:374:22)
    at ThinkDb.insert (C:\Users\59858\Desktop\think\think-ts-lib\dist\thinkdb.js:221:53)
    at say (C:\Users\59858\Desktop\think\think-ts\app\controller\hello.ts:13:41)
    at C:\Users\59858\Desktop\think\think-ts-lib\dist\router.js:49:50
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async exports.default (C:\Users\59858\Desktop\think\think-ts-lib\dist\error.js:12:9) {
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sql: "INSERT INTO sys_user (user_name, user_salt, created_time, update_time) VALUES ('测试1', 'asd', '2023-11-16 15:28:08', '2023-11-16 15:28:08')",
  sqlState: '42S22',
  sqlMessage: "Unknown column 'created_time' in 'field list'"
}
[2023-11-16T15:28:50.801] [ERROR] error - Error: Unknown column 'update_at' in 'field list'
    at PromisePool.execute (C:\Users\59858\Desktop\think\think-ts-lib\node_modules\mysql2\promise.js:374:22)
    at ThinkDb.insert (C:\Users\59858\Desktop\think\think-ts-lib\dist\thinkdb.js:221:53)
    at say (C:\Users\59858\Desktop\think\think-ts\app\controller\hello.ts:13:41)
    at C:\Users\59858\Desktop\think\think-ts-lib\dist\router.js:49:50
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async exports.default (C:\Users\59858\Desktop\think\think-ts-lib\dist\error.js:12:9) {
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sql: "INSERT INTO sys_user (user_name, user_salt, created_at, update_at) VALUES ('测试1', 'asd', '2023-11-16 15:28:50', '2023-11-16 15:28:50')",
  sqlState: '42S22',
  sqlMessage: "Unknown column 'update_at' in 'field list'"
}
[2023-11-16T15:30:02.617] [ERROR] error - Error: Data too long for column 'user_salt' at row 1
    at PromisePool.execute (C:\Users\59858\Desktop\think\think-ts-lib\node_modules\mysql2\promise.js:374:22)
    at ThinkDb.insertAll (C:\Users\59858\Desktop\think\think-ts-lib\dist\thinkdb.js:262:49)
    at say (C:\Users\59858\Desktop\think\think-ts\app\controller\hello.ts:13:41)
    at C:\Users\59858\Desktop\think\think-ts-lib\dist\router.js:49:50
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async exports.default (C:\Users\59858\Desktop\think\think-ts-lib\dist\error.js:12:9) {
  code: 'ER_DATA_TOO_LONG',
  errno: 1406,
  sql: "INSERT INTO sys_user (user_name, user_salt, created_at, updated_at) VALUES ('测试1', '2023-11-16 15:30:02', '2023-11-16 15:30:02', 'asd')",
  sqlState: '22001',
  sqlMessage: "Data too long for column 'user_salt' at row 1"
}
[2023-11-16T15:36:57.166] [ERROR] error - Error: Data too long for column 'user_salt' at row 1
    at PromisePool.execute (C:\Users\59858\Desktop\think\think-ts-lib\node_modules\mysql2\promise.js:374:22)
    at ThinkDb.insertAll (C:\Users\59858\Desktop\think\think-ts-lib\dist\thinkdb.js:262:49)
    at say (C:\Users\59858\Desktop\think\think-ts\app\controller\hello.ts:13:41)
    at C:\Users\59858\Desktop\think\think-ts-lib\dist\router.js:49:50
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async exports.default (C:\Users\59858\Desktop\think\think-ts-lib\dist\error.js:12:9) {
  code: 'ER_DATA_TOO_LONG',
  errno: 1406,
  sql: "INSERT INTO sys_user (user_name, user_salt, created_at, updated_at) VALUES ('测试2', '2023-11-16 15:36:57', '2023-11-16 15:36:57', 'asd')",
  sqlState: '22001',
  sqlMessage: "Data too long for column 'user_salt' at row 1"
}
[2023-11-16T15:40:05.868] [ERROR] error - Error: Data too long for column 'user_salt' at row 1
    at PromisePool.execute (C:\Users\59858\Desktop\think\think-ts-lib\node_modules\mysql2\promise.js:374:22)
    at ThinkDb.insertAll (C:\Users\59858\Desktop\think\think-ts-lib\dist\thinkdb.js:262:49)
    at say (C:\Users\59858\Desktop\think\think-ts\app\controller\hello.ts:13:41)
    at C:\Users\59858\Desktop\think\think-ts-lib\dist\router.js:49:50
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async exports.default (C:\Users\59858\Desktop\think\think-ts-lib\dist\error.js:12:9) {
  code: 'ER_DATA_TOO_LONG',
  errno: 1406,
  sql: "INSERT INTO sys_user (user_name, user_salt, created_at, updated_at) VALUES ('测试2', '2023-11-16 15:40:05', '2023-11-16 15:40:05', 'asd')",
  sqlState: '22001',
  sqlMessage: "Data too long for column 'user_salt' at row 1"
}
[2023-11-16T15:53:54.073] [ERROR] error - Error: Data too long for column 'user_salt' at row 1
    at PromisePool.execute (C:\Users\59858\Desktop\think\think-ts-lib\node_modules\mysql2\promise.js:374:22)
    at ThinkDb.insertAll (C:\Users\59858\Desktop\think\think-ts-lib\dist\thinkdb.js:259:49)
    at say (C:\Users\59858\Desktop\think\think-ts\app\controller\hello.ts:13:41)
    at C:\Users\59858\Desktop\think\think-ts-lib\dist\router.js:49:50
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async exports.default (C:\Users\59858\Desktop\think\think-ts-lib\dist\error.js:12:9) {
  code: 'ER_DATA_TOO_LONG',
  errno: 1406,
  sql: "INSERT INTO sys_user (user_name, user_salt, created_at, updated_at) VALUES ('测试2', '2023-11-16 15:53:54', '2023-11-16 15:53:54', 'asd')",
  sqlState: '22001',
  sqlMessage: "Data too long for column 'user_salt' at row 1"
}
[2023-11-16T15:57:13.621] [ERROR] error - Error: Data too long for column 'user_salt' at row 1
    at PromisePool.execute (C:\Users\59858\Desktop\think\think-ts-lib\node_modules\mysql2\promise.js:374:22)
    at ThinkDb.insertAll (C:\Users\59858\Desktop\think\think-ts-lib\dist\thinkdb.js:260:49)
    at say (C:\Users\59858\Desktop\think\think-ts\app\controller\hello.ts:13:41)
    at C:\Users\59858\Desktop\think\think-ts-lib\dist\router.js:49:50
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async exports.default (C:\Users\59858\Desktop\think\think-ts-lib\dist\error.js:12:9) {
  code: 'ER_DATA_TOO_LONG',
  errno: 1406,
  sql: "INSERT INTO sys_user (user_name, user_salt, created_at, updated_at) VALUES ('测试2', '2023-11-16 15:57:13', '2023-11-16 15:57:13', 'asd')",
  sqlState: '22001',
  sqlMessage: "Data too long for column 'user_salt' at row 1"
}
[2023-11-16T15:57:48.023] [ERROR] error - Error: Data too long for column 'user_salt' at row 1
    at PromisePool.execute (C:\Users\59858\Desktop\think\think-ts-lib\node_modules\mysql2\promise.js:374:22)
    at ThinkDb.insertAll (C:\Users\59858\Desktop\think\think-ts-lib\dist\thinkdb.js:260:49)
    at say (C:\Users\59858\Desktop\think\think-ts\app\controller\hello.ts:13:41)
    at C:\Users\59858\Desktop\think\think-ts-lib\dist\router.js:49:50
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async exports.default (C:\Users\59858\Desktop\think\think-ts-lib\dist\error.js:12:9) {
  code: 'ER_DATA_TOO_LONG',
  errno: 1406,
  sql: "INSERT INTO sys_user (user_name, user_salt, created_at, updated_at) VALUES ('测试2', '2023-11-16 15:57:47', '2023-11-16 15:57:47', 'asd')",
  sqlState: '22001',
  sqlMessage: "Data too long for column 'user_salt' at row 1"
}
[2023-11-16T16:06:32.630] [ERROR] error - Error: Data too long for column 'user_salt' at row 1
    at PromisePool.execute (C:\Users\59858\Desktop\think\think-ts-lib\node_modules\mysql2\promise.js:374:22)
    at ThinkDb.insertAll (C:\Users\59858\Desktop\think\think-ts-lib\dist\thinkdb.js:260:49)
    at say (C:\Users\59858\Desktop\think\think-ts\app\controller\hello.ts:13:41)
    at C:\Users\59858\Desktop\think\think-ts-lib\dist\router.js:49:50
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async exports.default (C:\Users\59858\Desktop\think\think-ts-lib\dist\error.js:12:9) {
  code: 'ER_DATA_TOO_LONG',
  errno: 1406,
  sql: "INSERT INTO sys_user (user_name, user_salt, created_at, updated_at) VALUES ('测试2', '2023-11-16 16:06:32', '2023-11-16 16:06:32', 'asd')",
  sqlState: '22001',
  sqlMessage: "Data too long for column 'user_salt' at row 1"
}
[2023-11-16T16:10:20.030] [ERROR] error - Error: Data too long for column 'user_salt' at row 1
    at PromisePool.execute (C:\Users\59858\Desktop\think\think-ts-lib\node_modules\mysql2\promise.js:374:22)
    at ThinkDb.insertAll (C:\Users\59858\Desktop\think\think-ts-lib\dist\thinkdb.js:260:49)
    at say (C:\Users\59858\Desktop\think\think-ts\app\controller\hello.ts:13:41)
    at C:\Users\59858\Desktop\think\think-ts-lib\dist\router.js:49:50
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async exports.default (C:\Users\59858\Desktop\think\think-ts-lib\dist\error.js:12:9) {
  code: 'ER_DATA_TOO_LONG',
  errno: 1406,
  sql: "INSERT INTO sys_user (user_name, user_salt, created_at, updated_at) VALUES ('测试2', '2023-11-16 16:10:19', '2023-11-16 16:10:19', 'asd')",
  sqlState: '22001',
  sqlMessage: "Data too long for column 'user_salt' at row 1"
}
[2023-11-16T16:11:44.158] [ERROR] error - Error: Malformed communication packet.
    at PromisePool.execute (C:\Users\59858\Desktop\think\think-ts-lib\node_modules\mysql2\promise.js:374:22)
    at ThinkDb.insertAll (C:\Users\59858\Desktop\think\think-ts-lib\dist\thinkdb.js:260:49)
    at say (C:\Users\59858\Desktop\think\think-ts\app\controller\hello.ts:13:41)
    at C:\Users\59858\Desktop\think\think-ts-lib\dist\router.js:49:50
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async exports.default (C:\Users\59858\Desktop\think\think-ts-lib\dist\error.js:12:9) {
  code: 'ER_MALFORMED_PACKET',
  errno: 1835,
  sql: "INSERT INTO sys_user (user_name, user_salt, created_at, updated_at) VALUES ('测试2', 'asd', ?, ?)",
  sqlState: 'HY000',
  sqlMessage: 'Malformed communication packet.'
}
[2023-11-16T16:13:01.844] [ERROR] error - Error: Data too long for column 'user_salt' at row 1
    at PromisePool.execute (C:\Users\59858\Desktop\think\think-ts-lib\node_modules\mysql2\promise.js:374:22)
    at ThinkDb.insertAll (C:\Users\59858\Desktop\think\think-ts-lib\dist\thinkdb.js:261:49)
    at say (C:\Users\59858\Desktop\think\think-ts\app\controller\hello.ts:13:41)
    at C:\Users\59858\Desktop\think\think-ts-lib\dist\router.js:49:50
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async exports.default (C:\Users\59858\Desktop\think\think-ts-lib\dist\error.js:12:9) {
  code: 'ER_DATA_TOO_LONG',
  errno: 1406,
  sql: "INSERT INTO sys_user (user_name, user_salt, created_at, updated_at) VALUES ('测试2', '2023-11-16 16:13:01', 'asd', '2023-11-16 16:13:01')",
  sqlState: '22001',
  sqlMessage: "Data too long for column 'user_salt' at row 1"
}
[2023-11-16T16:18:10.418] [ERROR] error - Error: Column count doesn't match value count at row 2
    at PromisePool.execute (C:\Users\59858\Desktop\think\think-ts-lib\node_modules\mysql2\promise.js:374:22)
    at ThinkDb.insertAll (C:\Users\59858\Desktop\think\think-ts-lib\dist\thinkdb.js:261:49)
    at say (C:\Users\59858\Desktop\think\think-ts\app\controller\hello.ts:13:41)
    at C:\Users\59858\Desktop\think\think-ts-lib\dist\router.js:49:50
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async exports.default (C:\Users\59858\Desktop\think\think-ts-lib\dist\error.js:12:9) {
  code: 'ER_WRONG_VALUE_COUNT_ON_ROW',
  errno: 1136,
  sql: "INSERT INTO sys_user (user_name, user_salt, created_at, updated_at) VALUES ('测试3', 'asd', '2023-11-16 16:18:10', '2023-11-16 16:18:10'),('测试4', 'asd')",
  sqlState: '21S01',
  sqlMessage: "Column count doesn't match value count at row 2"
}
[2023-11-16T17:11:40.497] [ERROR] error - Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ', updated_at = 9 WHERE id = '更新'' at line 1
    at PromisePool.execute (C:\Users\59858\Desktop\think\think-ts-lib\node_modules\mysql2\promise.js:374:22)
    at ThinkDb.update (C:\Users\59858\Desktop\think\think-ts-lib\dist\thinkdb.js:291:53)
    at say (C:\Users\59858\Desktop\think\think-ts\app\controller\hello.ts:13:56)
    at C:\Users\59858\Desktop\think\think-ts-lib\dist\router.js:49:50
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async exports.default (C:\Users\59858\Desktop\think\think-ts-lib\dist\error.js:12:9) {
  code: 'ER_PARSE_ERROR',
  errno: 1064,
  sql: "UPDATE sys_user SET user_name = , updated_at = 9 WHERE id = '更新' ",
  sqlState: '42000',
  sqlMessage: "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ', updated_at = 9 WHERE id = '更新'' at line 1"
}
[2023-11-16T17:19:37.541] [ERROR] error - Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ', updated_at = '2023-11-16 17:19:37' WHERE id = '更新'' at line 1
    at PromisePool.execute (C:\Users\59858\Desktop\think\think-ts-lib\node_modules\mysql2\promise.js:374:22)
    at ThinkDb.update (C:\Users\59858\Desktop\think\think-ts-lib\dist\thinkdb.js:291:53)
    at say (C:\Users\59858\Desktop\think\think-ts\app\controller\hello.ts:13:56)
    at C:\Users\59858\Desktop\think\think-ts-lib\dist\router.js:49:50
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async exports.default (C:\Users\59858\Desktop\think\think-ts-lib\dist\error.js:12:9) {
  code: 'ER_PARSE_ERROR',
  errno: 1064,
  sql: "UPDATE sys_user SET user_name = , updated_at = '2023-11-16 17:19:37' WHERE id = '更新' ",
  sqlState: '42000',
  sqlMessage: "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ', updated_at = '2023-11-16 17:19:37' WHERE id = '更新'' at line 1"
}
[2023-11-16T17:20:40.573] [ERROR] error - Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ', updated_at = '2023-11-16 17:20:40' WHERE id = '更新'' at line 1
    at PromisePool.execute (C:\Users\59858\Desktop\think\think-ts-lib\node_modules\mysql2\promise.js:374:22)
    at ThinkDb.update (C:\Users\59858\Desktop\think\think-ts-lib\dist\thinkdb.js:292:53)
    at say (C:\Users\59858\Desktop\think\think-ts\app\controller\hello.ts:13:56)
    at C:\Users\59858\Desktop\think\think-ts-lib\dist\router.js:49:50
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async exports.default (C:\Users\59858\Desktop\think\think-ts-lib\dist\error.js:12:9) {
  code: 'ER_PARSE_ERROR',
  errno: 1064,
  sql: "UPDATE sys_user SET user_name = , updated_at = '2023-11-16 17:20:40' WHERE id = '更新' ",
  sqlState: '42000',
  sqlMessage: "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ', updated_at = '2023-11-16 17:20:40' WHERE id = '更新'' at line 1"
}
[2023-11-16T17:22:10.680] [ERROR] error - Error: Incorrect datetime value: '更新' for column 'updated_at' at row 1
    at PromisePool.execute (C:\Users\59858\Desktop\think\think-ts-lib\node_modules\mysql2\promise.js:374:22)
    at ThinkDb.update (C:\Users\59858\Desktop\think\think-ts-lib\dist\thinkdb.js:292:53)
    at say (C:\Users\59858\Desktop\think\think-ts\app\controller\hello.ts:13:56)
    at C:\Users\59858\Desktop\think\think-ts-lib\dist\router.js:49:50
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async exports.default (C:\Users\59858\Desktop\think\think-ts-lib\dist\error.js:12:9) {
  code: 'ER_TRUNCATED_WRONG_VALUE',
  errno: 1292,
  sql: "UPDATE sys_user SET user_name = '2023-11-16 17:22:10', updated_at = '更新' WHERE id = 9 ",
  sqlState: '22007',
  sqlMessage: "Incorrect datetime value: '更新' for column 'updated_at' at row 1"
}
[2023-11-16T18:03:00.962] [ERROR] error - Error: Unknown column 'delete_time' in 'field list'
    at PromisePool.execute (C:\Users\59858\Desktop\think\think-ts-lib\node_modules\mysql2\promise.js:374:22)
    at ThinkDb.update (C:\Users\59858\Desktop\think\think-ts-lib\dist\thinkdb.js:293:53)
    at ThinkDb.delete (C:\Users\59858\Desktop\think\think-ts-lib\dist\thinkdb.js:309:31)
    at say (C:\Users\59858\Desktop\think\think-ts\app\controller\hello.ts:13:62)
    at C:\Users\59858\Desktop\think\think-ts-lib\dist\router.js:49:50
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async exports.default (C:\Users\59858\Desktop\think\think-ts-lib\dist\error.js:12:9) {
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sql: "UPDATE sys_user SET delete_time = '2023-11-16 18:03:00' WHERE id = 9 ",
  sqlState: '42S22',
  sqlMessage: "Unknown column 'delete_time' in 'field list'"
}
[2023-11-16T18:04:04.510] [ERROR] error - Error: Unknown column 'delete_time' in 'field list'
    at PromisePool.execute (C:\Users\59858\Desktop\think\think-ts-lib\node_modules\mysql2\promise.js:374:22)
    at ThinkDb.update (C:\Users\59858\Desktop\think\think-ts-lib\dist\thinkdb.js:293:53)
    at ThinkDb.delete (C:\Users\59858\Desktop\think\think-ts-lib\dist\thinkdb.js:309:31)
    at say (C:\Users\59858\Desktop\think\think-ts\app\controller\hello.ts:13:62)
    at C:\Users\59858\Desktop\think\think-ts-lib\dist\router.js:49:50
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async exports.default (C:\Users\59858\Desktop\think\think-ts-lib\dist\error.js:12:9) {
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sql: "UPDATE sys_user SET delete_time = '2023-11-16 18:04:04' WHERE id = 9 ",
  sqlState: '42S22',
  sqlMessage: "Unknown column 'delete_time' in 'field list'"
}
